In [33]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

import warnings #<--- to hide the pink warning box!
warnings.filterwarnings('ignore')

In [34]:
X = np.array([
    [1,3500], #unfit
    [2,3200], #unfit
    [3,3000], #unfit
    [4,2500], #fit
    [5,2300], #fit
    [6,2000], #fit
    [7,2200], #fit
    [8,3700], #unfit
])
y = ['Unfit','Unfit','Unfit','Fit','Fit','Fit','Fit','Unfit',]

In [35]:
model=KNeighborsClassifier(n_neighbors=3)

In [36]:
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [37]:
new_person = [[4.5,2600]]
pred = model.predict(new_person)
print('Predicted Result: ',pred[0])

Predicted Result:  Fit

In [39]:
exercise_hours=float(input("Enter number of exercise hours: "))
cal_intake=float(input("Enter number of calories consumed: "))
pred_fu=model.predict([[exercise_hours,cal_intake]])
print(f'Exercise Hours {exercise_hours}, Calories Intake {cal_intake} You are likely {pred_fu[0]}')

Enter number of exercise hours:  2.5
Enter number of calories consumed:  3500

Exercise Hours 2.5, Calories Intake 3500.0 You are likely Unfit

In [40]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

In [41]:
df = pd.read_csv('fruit_data.csv')
df.head(5)

   Weight  Size   Fruit
0     150   7.0   Apple
1     160   7.2   Apple
2     200   8.0  Orange
3     210   8.2  Orange
4     180   7.5       ?

In [42]:
num_rows = len(df)
print(f"Number of rows: {num_rows}")

Number of rows: 5

In [43]:
print('Number of Missing Values are:',df.isnull().sum())

Number of Missing Values are: Weight    0
Size      0
Fruit     0
dtype: int64

In [44]:
X = df[['Weight','Size']]
y= df['Fruit']

In [45]:
model=KNeighborsClassifier(n_neighbors=3)

In [46]:
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [48]:
weight=float(input("Enter the fruit weight (g): "))
size=float(input("Enter the fruit size (cm): "))
prediction=model.predict([[weight,size]])
print(f'With weight of {weight} and size of fruit {size} very likely the fruit is {prediction[0]}')

Enter the fruit weight (g):  167
Enter the fruit size (cm):  8.2

With weight of 167.0 and size of fruit 8.2 very likely the fruit is Apple

In [49]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

In [50]:
df = pd.read_csv('student_grade.csv')
df.head(5)

   Hours_Studied  Assignments_Completed Grade
0            1.5                      1     C
1            2.0                      2     C
2            3.0                      3     B
3            4.0                      4     B
4            5.0                      5     A

In [51]:
num_rows = len(df)
print(f"Number of rows: {num_rows}")

Number of rows: 6

In [52]:
print('Number of Missing Values are:',df.isnull().sum())

Number of Missing Values are: Hours_Studied            0
Assignments_Completed    0
Grade                    0
dtype: int64

In [53]:
X = df[['Hours_Studied','Assignments_Completed']]
y= df['Grade']

In [54]:
model=KNeighborsClassifier(n_neighbors=3)

In [55]:
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [56]:
hours=float(input("Enter the hours allocated to study: "))
assignment=float(input("Enter how many assignment completed: "))
prediction=model.predict([[hours,assignment]])
print(f'With hours spent to study of {hours} and assignment completed {assignment} very likely to get grade {prediction[0]}')

Enter the hours allocated to study:  3.5
Enter how many assignment completed:  4

With hours spent to study of 3.5 and assignment completed 4.0 very likely to get grade B