In [118]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error,r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [119]:
data = pd.DataFrame({
    "Experience": [1,2,3,4,5,np.nan,7,8,9,10],
    "Education": ["Bachelor's","Master's","Master's","PhD","Bachelor's",np.nan,"Bachelor's","Master's","PhD","Bachelor's"],
    "Salary": [35000,40000,45000,55000,50000,50000,62000,70000,75000,80000]
})
data

   Experience   Education  Salary
0         1.0  Bachelor's   35000
1         2.0    Master's   40000
2         3.0    Master's   45000
3         4.0         PhD   55000
4         5.0  Bachelor's   50000
5         NaN         NaN   50000
6         7.0  Bachelor's   62000
7         8.0    Master's   70000
8         9.0         PhD   75000
9        10.0  Bachelor's   80000

In [120]:
X= data [["Experience","Education"]]
y= data ["Salary"]

In [121]:
num_cols=["Experience"]
cat_cols=["Education"]
numeric=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="mean")),
    ("scaler",StandardScaler())
])
numeric

categorical=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("encoder",OneHotEncoder(handle_unknown="ignore"))
])
categorical

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [122]:
preprocess=ColumnTransformer([("num",numeric,num_cols),
                             ("cat",categorical,cat_cols)
                             ])
model = Pipeline(steps=[
                 ("preprocess",preprocess),
                 ("model",LinearRegression())
])

In [123]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Experience']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Education'])])),
                ('model', LinearRegression())])

In [124]:
y_pred=model.predict(X_test)
y_pred

array([80119.49987091, 39916.35009036])

In [125]:
#Evaluate the Model
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

print("Mean Absolute Error is:",mae)
print("Mean Squared Error is:",mse)
print("Root Mean Squared Error is:",rmse)
print("R-Squared is:",r2)

Mean Absolute Error is: 2601.574890274038
Mean Squared Error is: 13108138.117818153
Root Mean Squared Error is: 3620.5162778004674
R-Squared is: 0.9571979163499815

In [126]:
# Predict for a new employee
exp = int(input("Enter the experience \t"))
edu = input("Enter the education level \t")

new_employee=pd.DataFrame({
    "Experience":[exp],
    "Education":[edu]
})


predict_salary=model.predict(new_employee)
print("Predicted Salary for the new employee:",round(predict_salary[0],2))

Enter the experience 	3
Enter the education level 	PhD
Predicted Salary for the new employee: 49976.1

Build a Machine Learning Pipeline to predict Fuel Efficancy(km/l) of a car based on Engine Size, Horse Power, and Fuel Type. Evaluate the model as well i.e mae, rmse, r-2

In [127]:
data = pd.DataFrame({
    "EngineSize": [1.0, 1.2, 1.4, 1.6, 1.8, np.nan, 2.0, 2.2, 2.4, 2.6],
    "HorsePower": [68, 75, 90, 100, 110, 115, np.nan, 130, 150, 160],
    "FuelType": ["Petrol", "Diesel", "Petrol", "Diesel", "Petrol",
                 "Petrol", np.nan, "Diesel", "Petrol", "Diesel"],
    "FuelEfficiency": [20, 22, 19, 25, 18, 21, 23, 26, 17, 24]
})

data

   EngineSize  HorsePower FuelType  FuelEfficiency
0         1.0        68.0   Petrol              20
1         1.2        75.0   Diesel              22
2         1.4        90.0   Petrol              19
3         1.6       100.0   Diesel              25
4         1.8       110.0   Petrol              18
5         NaN       115.0   Petrol              21
6         2.0         NaN      NaN              23
7         2.2       130.0   Diesel              26
8         2.4       150.0   Petrol              17
9         2.6       160.0   Diesel              24

In [128]:
x = data[["EngineSize","HorsePower","FuelType"]]
y = data["FuelEfficiency"]

In [129]:
num_cols=["EngineSize","HorsePower"]
cat_cols=["FuelType"]
numeric=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="mean")),
    ("scaler",StandardScaler())
])
numeric

categorical=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("encoder",OneHotEncoder(handle_unknown="ignore"))
])
categorical

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [130]:
preprocess=ColumnTransformer([("num",numeric,num_cols),
                             ("cat",categorical,cat_cols)
                             ])
model = Pipeline(steps=[
                 ("preprocess",preprocess),
                 ("model",LinearRegression())
])

In [131]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['EngineSize', 'HorsePower']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['FuelType'])])),
                ('model', LinearRegression())])

In [132]:
y_pred=model.predict(x_test)
y_pred

array([18.89758649, 25.53470785])

In [133]:
#Evaluate the Model
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

print("Mean Absolute Error is:",mae)
print("Mean Squared Error is:",mse)
print("Root Mean Squared Error is:",rmse)
print("R-Squared is:",round(r2,2))

Mean Absolute Error is: 2.716147167154137
Mean Squared Error is: 8.047497018648478
Root Mean Squared Error is: 2.836811065025036
R-Squared is: -0.29

In [136]:
# Predict for a new vehicle
Engine_Size = float(input("Enter EngineSize for the new vehicle \t"))
Horse_Power = int(input("Enter HorsePower for the new vehicle  \t"))
Fuel_Type = input("Enter FuelType for the new vehicle \t")

new_vehicle=pd.DataFrame({
    "EngineSize":[Engine_Size],
    "HorsePower":[Horse_Power],
    "FuelType":[Fuel_Type]
})
predict_eff=model.predict(new_vehicle)
print("Predicted Marks for the new students:",round(predict_eff[0],2))

Enter EngineSize for the new vehicle 	1.6
Enter HorsePower for the new vehicle  	130
Enter FuelType for the new vehicle 	Diesel
Predicted Marks for the new students: 18.95